package com.nttdata.fhir.model.mybatis;

import com.nttdata.fhir.model.DataObject;
import java.io.Serializable;

public class AppUserVO extends DataObject implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column appuser.id
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column appuser.username
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column appuser.firstName
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	private String firstName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column appuser.lastName
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	private String lastName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column appuser.email
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column appuser.password
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column appuser.isActive
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	private Boolean isActive;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table appuser
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column appuser.id
	 * @return  the value of appuser.id
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column appuser.id
	 * @param id  the value for appuser.id
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column appuser.username
	 * @return  the value of appuser.username
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column appuser.username
	 * @param username  the value for appuser.username
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column appuser.firstName
	 * @return  the value of appuser.firstName
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column appuser.firstName
	 * @param firstName  the value for appuser.firstName
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName == null ? null : firstName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column appuser.lastName
	 * @return  the value of appuser.lastName
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	public String getLastName() {
		return lastName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column appuser.lastName
	 * @param lastName  the value for appuser.lastName
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName == null ? null : lastName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column appuser.email
	 * @return  the value of appuser.email
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column appuser.email
	 * @param email  the value for appuser.email
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column appuser.password
	 * @return  the value of appuser.password
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column appuser.password
	 * @param password  the value for appuser.password
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column appuser.isActive
	 * @return  the value of appuser.isActive
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	public Boolean getIsActive() {
		return isActive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column appuser.isActive
	 * @param isActive  the value for appuser.isActive
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}
}