package com.nttdata.fhir.model.mybatis;

import com.nttdata.fhir.model.DataObject;
import java.io.Serializable;
import java.util.Date;

public class BaseProfileTypeVO extends DataObject implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column baseprofiletype.id
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column baseprofiletype.profileName
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	private String profileName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column baseprofiletype.isActive
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	private Boolean isActive;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column baseprofiletype.description
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column baseprofiletype.status
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column baseprofiletype.additionalNotes
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	private String additionalNotes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column baseprofiletype.ownerName
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	private String ownerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column baseprofiletype.organization
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	private String organization;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column baseprofiletype.accessModifier
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	private String accessModifier;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column baseprofiletype.locationUrl
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	private String locationUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column baseprofiletype.parentProfileName
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	private String parentProfileName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column baseprofiletype.IsBaseProfile
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	private Boolean isBaseProfile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table baseprofiletype
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column baseprofiletype.id
	 * @return  the value of baseprofiletype.id
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column baseprofiletype.id
	 * @param id  the value for baseprofiletype.id
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column baseprofiletype.profileName
	 * @return  the value of baseprofiletype.profileName
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public String getProfileName() {
		return profileName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column baseprofiletype.profileName
	 * @param profileName  the value for baseprofiletype.profileName
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public void setProfileName(String profileName) {
		this.profileName = profileName == null ? null : profileName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column baseprofiletype.isActive
	 * @return  the value of baseprofiletype.isActive
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public Boolean getIsActive() {
		return isActive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column baseprofiletype.isActive
	 * @param isActive  the value for baseprofiletype.isActive
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column baseprofiletype.description
	 * @return  the value of baseprofiletype.description
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column baseprofiletype.description
	 * @param description  the value for baseprofiletype.description
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column baseprofiletype.status
	 * @return  the value of baseprofiletype.status
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column baseprofiletype.status
	 * @param status  the value for baseprofiletype.status
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column baseprofiletype.additionalNotes
	 * @return  the value of baseprofiletype.additionalNotes
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public String getAdditionalNotes() {
		return additionalNotes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column baseprofiletype.additionalNotes
	 * @param additionalNotes  the value for baseprofiletype.additionalNotes
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public void setAdditionalNotes(String additionalNotes) {
		this.additionalNotes = additionalNotes == null ? null : additionalNotes.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column baseprofiletype.ownerName
	 * @return  the value of baseprofiletype.ownerName
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public String getOwnerName() {
		return ownerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column baseprofiletype.ownerName
	 * @param ownerName  the value for baseprofiletype.ownerName
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public void setOwnerName(String ownerName) {
		this.ownerName = ownerName == null ? null : ownerName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column baseprofiletype.organization
	 * @return  the value of baseprofiletype.organization
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public String getOrganization() {
		return organization;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column baseprofiletype.organization
	 * @param organization  the value for baseprofiletype.organization
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public void setOrganization(String organization) {
		this.organization = organization == null ? null : organization.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column baseprofiletype.accessModifier
	 * @return  the value of baseprofiletype.accessModifier
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public String getAccessModifier() {
		return accessModifier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column baseprofiletype.accessModifier
	 * @param accessModifier  the value for baseprofiletype.accessModifier
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public void setAccessModifier(String accessModifier) {
		this.accessModifier = accessModifier == null ? null : accessModifier.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column baseprofiletype.locationUrl
	 * @return  the value of baseprofiletype.locationUrl
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public String getLocationUrl() {
		return locationUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column baseprofiletype.locationUrl
	 * @param locationUrl  the value for baseprofiletype.locationUrl
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public void setLocationUrl(String locationUrl) {
		this.locationUrl = locationUrl == null ? null : locationUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column baseprofiletype.parentProfileName
	 * @return  the value of baseprofiletype.parentProfileName
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public String getParentProfileName() {
		return parentProfileName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column baseprofiletype.parentProfileName
	 * @param parentProfileName  the value for baseprofiletype.parentProfileName
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public void setParentProfileName(String parentProfileName) {
		this.parentProfileName = parentProfileName == null ? null : parentProfileName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column baseprofiletype.IsBaseProfile
	 * @return  the value of baseprofiletype.IsBaseProfile
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public Boolean getIsBaseProfile() {
		return isBaseProfile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column baseprofiletype.IsBaseProfile
	 * @param isBaseProfile  the value for baseprofiletype.IsBaseProfile
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public void setIsBaseProfile(Boolean isBaseProfile) {
		this.isBaseProfile = isBaseProfile;
	}
}