package com.nttdata.fhir.model.mybatis;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BaseProfileTypeVOExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table baseprofiletype
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table baseprofiletype
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table baseprofiletype
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table baseprofiletype
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	public BaseProfileTypeVOExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table baseprofiletype
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table baseprofiletype
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table baseprofiletype
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table baseprofiletype
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table baseprofiletype
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table baseprofiletype
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table baseprofiletype
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table baseprofiletype
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table baseprofiletype
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table baseprofiletype
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table baseprofiletype
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("baseprofiletype.id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("baseprofiletype.id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("baseprofiletype.id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("baseprofiletype.id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("baseprofiletype.id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("baseprofiletype.id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("baseprofiletype.id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("baseprofiletype.id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("baseprofiletype.id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("baseprofiletype.id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("baseprofiletype.id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("baseprofiletype.id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andProfileNameIsNull() {
			addCriterion("baseprofiletype.profileName is null");
			return (Criteria) this;
		}

		public Criteria andProfileNameIsNotNull() {
			addCriterion("baseprofiletype.profileName is not null");
			return (Criteria) this;
		}

		public Criteria andProfileNameEqualTo(String value) {
			addCriterion("baseprofiletype.profileName =", value, "profileName");
			return (Criteria) this;
		}

		public Criteria andProfileNameNotEqualTo(String value) {
			addCriterion("baseprofiletype.profileName <>", value, "profileName");
			return (Criteria) this;
		}

		public Criteria andProfileNameGreaterThan(String value) {
			addCriterion("baseprofiletype.profileName >", value, "profileName");
			return (Criteria) this;
		}

		public Criteria andProfileNameGreaterThanOrEqualTo(String value) {
			addCriterion("baseprofiletype.profileName >=", value, "profileName");
			return (Criteria) this;
		}

		public Criteria andProfileNameLessThan(String value) {
			addCriterion("baseprofiletype.profileName <", value, "profileName");
			return (Criteria) this;
		}

		public Criteria andProfileNameLessThanOrEqualTo(String value) {
			addCriterion("baseprofiletype.profileName <=", value, "profileName");
			return (Criteria) this;
		}

		public Criteria andProfileNameLike(String value) {
			addCriterion("baseprofiletype.profileName like", value, "profileName");
			return (Criteria) this;
		}

		public Criteria andProfileNameNotLike(String value) {
			addCriterion("baseprofiletype.profileName not like", value, "profileName");
			return (Criteria) this;
		}

		public Criteria andProfileNameIn(List<String> values) {
			addCriterion("baseprofiletype.profileName in", values, "profileName");
			return (Criteria) this;
		}

		public Criteria andProfileNameNotIn(List<String> values) {
			addCriterion("baseprofiletype.profileName not in", values, "profileName");
			return (Criteria) this;
		}

		public Criteria andProfileNameBetween(String value1, String value2) {
			addCriterion("baseprofiletype.profileName between", value1, value2, "profileName");
			return (Criteria) this;
		}

		public Criteria andProfileNameNotBetween(String value1, String value2) {
			addCriterion("baseprofiletype.profileName not between", value1, value2, "profileName");
			return (Criteria) this;
		}

		public Criteria andIsActiveIsNull() {
			addCriterion("baseprofiletype.isActive is null");
			return (Criteria) this;
		}

		public Criteria andIsActiveIsNotNull() {
			addCriterion("baseprofiletype.isActive is not null");
			return (Criteria) this;
		}

		public Criteria andIsActiveEqualTo(Boolean value) {
			addCriterion("baseprofiletype.isActive =", value, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveNotEqualTo(Boolean value) {
			addCriterion("baseprofiletype.isActive <>", value, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveGreaterThan(Boolean value) {
			addCriterion("baseprofiletype.isActive >", value, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveGreaterThanOrEqualTo(Boolean value) {
			addCriterion("baseprofiletype.isActive >=", value, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveLessThan(Boolean value) {
			addCriterion("baseprofiletype.isActive <", value, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveLessThanOrEqualTo(Boolean value) {
			addCriterion("baseprofiletype.isActive <=", value, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveIn(List<Boolean> values) {
			addCriterion("baseprofiletype.isActive in", values, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveNotIn(List<Boolean> values) {
			addCriterion("baseprofiletype.isActive not in", values, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveBetween(Boolean value1, Boolean value2) {
			addCriterion("baseprofiletype.isActive between", value1, value2, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveNotBetween(Boolean value1, Boolean value2) {
			addCriterion("baseprofiletype.isActive not between", value1, value2, "isActive");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNull() {
			addCriterion("baseprofiletype.description is null");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNotNull() {
			addCriterion("baseprofiletype.description is not null");
			return (Criteria) this;
		}

		public Criteria andDescriptionEqualTo(String value) {
			addCriterion("baseprofiletype.description =", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotEqualTo(String value) {
			addCriterion("baseprofiletype.description <>", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThan(String value) {
			addCriterion("baseprofiletype.description >", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("baseprofiletype.description >=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThan(String value) {
			addCriterion("baseprofiletype.description <", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThanOrEqualTo(String value) {
			addCriterion("baseprofiletype.description <=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLike(String value) {
			addCriterion("baseprofiletype.description like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotLike(String value) {
			addCriterion("baseprofiletype.description not like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionIn(List<String> values) {
			addCriterion("baseprofiletype.description in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotIn(List<String> values) {
			addCriterion("baseprofiletype.description not in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionBetween(String value1, String value2) {
			addCriterion("baseprofiletype.description between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotBetween(String value1, String value2) {
			addCriterion("baseprofiletype.description not between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andCreatedOnIsNull() {
			addCriterion("baseprofiletype.createdOn is null");
			return (Criteria) this;
		}

		public Criteria andCreatedOnIsNotNull() {
			addCriterion("baseprofiletype.createdOn is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedOnEqualTo(Date value) {
			addCriterion("baseprofiletype.createdOn =", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnNotEqualTo(Date value) {
			addCriterion("baseprofiletype.createdOn <>", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnGreaterThan(Date value) {
			addCriterion("baseprofiletype.createdOn >", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnGreaterThanOrEqualTo(Date value) {
			addCriterion("baseprofiletype.createdOn >=", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnLessThan(Date value) {
			addCriterion("baseprofiletype.createdOn <", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnLessThanOrEqualTo(Date value) {
			addCriterion("baseprofiletype.createdOn <=", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnIn(List<Date> values) {
			addCriterion("baseprofiletype.createdOn in", values, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnNotIn(List<Date> values) {
			addCriterion("baseprofiletype.createdOn not in", values, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnBetween(Date value1, Date value2) {
			addCriterion("baseprofiletype.createdOn between", value1, value2, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnNotBetween(Date value1, Date value2) {
			addCriterion("baseprofiletype.createdOn not between", value1, value2, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedByIsNull() {
			addCriterion("baseprofiletype.createdBy is null");
			return (Criteria) this;
		}

		public Criteria andCreatedByIsNotNull() {
			addCriterion("baseprofiletype.createdBy is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedByEqualTo(String value) {
			addCriterion("baseprofiletype.createdBy =", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByNotEqualTo(String value) {
			addCriterion("baseprofiletype.createdBy <>", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByGreaterThan(String value) {
			addCriterion("baseprofiletype.createdBy >", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
			addCriterion("baseprofiletype.createdBy >=", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByLessThan(String value) {
			addCriterion("baseprofiletype.createdBy <", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByLessThanOrEqualTo(String value) {
			addCriterion("baseprofiletype.createdBy <=", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByLike(String value) {
			addCriterion("baseprofiletype.createdBy like", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByNotLike(String value) {
			addCriterion("baseprofiletype.createdBy not like", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByIn(List<String> values) {
			addCriterion("baseprofiletype.createdBy in", values, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByNotIn(List<String> values) {
			addCriterion("baseprofiletype.createdBy not in", values, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByBetween(String value1, String value2) {
			addCriterion("baseprofiletype.createdBy between", value1, value2, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByNotBetween(String value1, String value2) {
			addCriterion("baseprofiletype.createdBy not between", value1, value2, "createdBy");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table baseprofiletype
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table baseprofiletype
     *
     * @mbg.generated do_not_delete_during_merge Thu Jan 18 15:55:27 IST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}