package com.nttdata.fhir.model.mybatis;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Iterator;

public class BaseProfileTypeVOExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table baseprofiletype
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table baseprofiletype
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table baseprofiletype
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table baseprofiletype
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public BaseProfileTypeVOExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table baseprofiletype
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table baseprofiletype
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table baseprofiletype
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table baseprofiletype
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table baseprofiletype
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table baseprofiletype
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table baseprofiletype
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table baseprofiletype
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table baseprofiletype
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table baseprofiletype
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table baseprofiletype
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("baseprofiletype.id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("baseprofiletype.id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("baseprofiletype.id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("baseprofiletype.id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("baseprofiletype.id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("baseprofiletype.id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("baseprofiletype.id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("baseprofiletype.id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("baseprofiletype.id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("baseprofiletype.id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("baseprofiletype.id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("baseprofiletype.id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andProfileNameIsNull() {
			addCriterion("baseprofiletype.profileName is null");
			return (Criteria) this;
		}

		public Criteria andProfileNameIsNotNull() {
			addCriterion("baseprofiletype.profileName is not null");
			return (Criteria) this;
		}

		public Criteria andProfileNameEqualTo(String value) {
			addCriterion("baseprofiletype.profileName =", value, "profileName");
			return (Criteria) this;
		}

		public Criteria andProfileNameNotEqualTo(String value) {
			addCriterion("baseprofiletype.profileName <>", value, "profileName");
			return (Criteria) this;
		}

		public Criteria andProfileNameGreaterThan(String value) {
			addCriterion("baseprofiletype.profileName >", value, "profileName");
			return (Criteria) this;
		}

		public Criteria andProfileNameGreaterThanOrEqualTo(String value) {
			addCriterion("baseprofiletype.profileName >=", value, "profileName");
			return (Criteria) this;
		}

		public Criteria andProfileNameLessThan(String value) {
			addCriterion("baseprofiletype.profileName <", value, "profileName");
			return (Criteria) this;
		}

		public Criteria andProfileNameLessThanOrEqualTo(String value) {
			addCriterion("baseprofiletype.profileName <=", value, "profileName");
			return (Criteria) this;
		}

		public Criteria andProfileNameLike(String value) {
			addCriterion("baseprofiletype.profileName like", value, "profileName");
			return (Criteria) this;
		}

		public Criteria andProfileNameNotLike(String value) {
			addCriterion("baseprofiletype.profileName not like", value, "profileName");
			return (Criteria) this;
		}

		public Criteria andProfileNameIn(List<String> values) {
			addCriterion("baseprofiletype.profileName in", values, "profileName");
			return (Criteria) this;
		}

		public Criteria andProfileNameNotIn(List<String> values) {
			addCriterion("baseprofiletype.profileName not in", values, "profileName");
			return (Criteria) this;
		}

		public Criteria andProfileNameBetween(String value1, String value2) {
			addCriterion("baseprofiletype.profileName between", value1, value2, "profileName");
			return (Criteria) this;
		}

		public Criteria andProfileNameNotBetween(String value1, String value2) {
			addCriterion("baseprofiletype.profileName not between", value1, value2, "profileName");
			return (Criteria) this;
		}

		public Criteria andIsActiveIsNull() {
			addCriterion("baseprofiletype.isActive is null");
			return (Criteria) this;
		}

		public Criteria andIsActiveIsNotNull() {
			addCriterion("baseprofiletype.isActive is not null");
			return (Criteria) this;
		}

		public Criteria andIsActiveEqualTo(Boolean value) {
			addCriterion("baseprofiletype.isActive =", value, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveNotEqualTo(Boolean value) {
			addCriterion("baseprofiletype.isActive <>", value, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveGreaterThan(Boolean value) {
			addCriterion("baseprofiletype.isActive >", value, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveGreaterThanOrEqualTo(Boolean value) {
			addCriterion("baseprofiletype.isActive >=", value, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveLessThan(Boolean value) {
			addCriterion("baseprofiletype.isActive <", value, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveLessThanOrEqualTo(Boolean value) {
			addCriterion("baseprofiletype.isActive <=", value, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveIn(List<Boolean> values) {
			addCriterion("baseprofiletype.isActive in", values, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveNotIn(List<Boolean> values) {
			addCriterion("baseprofiletype.isActive not in", values, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveBetween(Boolean value1, Boolean value2) {
			addCriterion("baseprofiletype.isActive between", value1, value2, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveNotBetween(Boolean value1, Boolean value2) {
			addCriterion("baseprofiletype.isActive not between", value1, value2, "isActive");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNull() {
			addCriterion("baseprofiletype.description is null");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNotNull() {
			addCriterion("baseprofiletype.description is not null");
			return (Criteria) this;
		}

		public Criteria andDescriptionEqualTo(String value) {
			addCriterion("baseprofiletype.description =", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotEqualTo(String value) {
			addCriterion("baseprofiletype.description <>", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThan(String value) {
			addCriterion("baseprofiletype.description >", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("baseprofiletype.description >=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThan(String value) {
			addCriterion("baseprofiletype.description <", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThanOrEqualTo(String value) {
			addCriterion("baseprofiletype.description <=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLike(String value) {
			addCriterion("baseprofiletype.description like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotLike(String value) {
			addCriterion("baseprofiletype.description not like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionIn(List<String> values) {
			addCriterion("baseprofiletype.description in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotIn(List<String> values) {
			addCriterion("baseprofiletype.description not in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionBetween(String value1, String value2) {
			addCriterion("baseprofiletype.description between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotBetween(String value1, String value2) {
			addCriterion("baseprofiletype.description not between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andCreatedOnIsNull() {
			addCriterion("baseprofiletype.createdOn is null");
			return (Criteria) this;
		}

		public Criteria andCreatedOnIsNotNull() {
			addCriterion("baseprofiletype.createdOn is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedOnEqualTo(Date value) {
			addCriterionForJDBCDate("baseprofiletype.createdOn =", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnNotEqualTo(Date value) {
			addCriterionForJDBCDate("baseprofiletype.createdOn <>", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnGreaterThan(Date value) {
			addCriterionForJDBCDate("baseprofiletype.createdOn >", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("baseprofiletype.createdOn >=", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnLessThan(Date value) {
			addCriterionForJDBCDate("baseprofiletype.createdOn <", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("baseprofiletype.createdOn <=", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnIn(List<Date> values) {
			addCriterionForJDBCDate("baseprofiletype.createdOn in", values, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnNotIn(List<Date> values) {
			addCriterionForJDBCDate("baseprofiletype.createdOn not in", values, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("baseprofiletype.createdOn between", value1, value2, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("baseprofiletype.createdOn not between", value1, value2, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedByIsNull() {
			addCriterion("baseprofiletype.createdBy is null");
			return (Criteria) this;
		}

		public Criteria andCreatedByIsNotNull() {
			addCriterion("baseprofiletype.createdBy is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedByEqualTo(String value) {
			addCriterion("baseprofiletype.createdBy =", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByNotEqualTo(String value) {
			addCriterion("baseprofiletype.createdBy <>", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByGreaterThan(String value) {
			addCriterion("baseprofiletype.createdBy >", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
			addCriterion("baseprofiletype.createdBy >=", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByLessThan(String value) {
			addCriterion("baseprofiletype.createdBy <", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByLessThanOrEqualTo(String value) {
			addCriterion("baseprofiletype.createdBy <=", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByLike(String value) {
			addCriterion("baseprofiletype.createdBy like", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByNotLike(String value) {
			addCriterion("baseprofiletype.createdBy not like", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByIn(List<String> values) {
			addCriterion("baseprofiletype.createdBy in", values, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByNotIn(List<String> values) {
			addCriterion("baseprofiletype.createdBy not in", values, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByBetween(String value1, String value2) {
			addCriterion("baseprofiletype.createdBy between", value1, value2, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByNotBetween(String value1, String value2) {
			addCriterion("baseprofiletype.createdBy not between", value1, value2, "createdBy");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("baseprofiletype.status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("baseprofiletype.status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("baseprofiletype.status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("baseprofiletype.status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("baseprofiletype.status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("baseprofiletype.status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("baseprofiletype.status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("baseprofiletype.status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("baseprofiletype.status like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("baseprofiletype.status not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("baseprofiletype.status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("baseprofiletype.status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("baseprofiletype.status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("baseprofiletype.status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andAdditionalNotesIsNull() {
			addCriterion("baseprofiletype.additionalNotes is null");
			return (Criteria) this;
		}

		public Criteria andAdditionalNotesIsNotNull() {
			addCriterion("baseprofiletype.additionalNotes is not null");
			return (Criteria) this;
		}

		public Criteria andAdditionalNotesEqualTo(String value) {
			addCriterion("baseprofiletype.additionalNotes =", value, "additionalNotes");
			return (Criteria) this;
		}

		public Criteria andAdditionalNotesNotEqualTo(String value) {
			addCriterion("baseprofiletype.additionalNotes <>", value, "additionalNotes");
			return (Criteria) this;
		}

		public Criteria andAdditionalNotesGreaterThan(String value) {
			addCriterion("baseprofiletype.additionalNotes >", value, "additionalNotes");
			return (Criteria) this;
		}

		public Criteria andAdditionalNotesGreaterThanOrEqualTo(String value) {
			addCriterion("baseprofiletype.additionalNotes >=", value, "additionalNotes");
			return (Criteria) this;
		}

		public Criteria andAdditionalNotesLessThan(String value) {
			addCriterion("baseprofiletype.additionalNotes <", value, "additionalNotes");
			return (Criteria) this;
		}

		public Criteria andAdditionalNotesLessThanOrEqualTo(String value) {
			addCriterion("baseprofiletype.additionalNotes <=", value, "additionalNotes");
			return (Criteria) this;
		}

		public Criteria andAdditionalNotesLike(String value) {
			addCriterion("baseprofiletype.additionalNotes like", value, "additionalNotes");
			return (Criteria) this;
		}

		public Criteria andAdditionalNotesNotLike(String value) {
			addCriterion("baseprofiletype.additionalNotes not like", value, "additionalNotes");
			return (Criteria) this;
		}

		public Criteria andAdditionalNotesIn(List<String> values) {
			addCriterion("baseprofiletype.additionalNotes in", values, "additionalNotes");
			return (Criteria) this;
		}

		public Criteria andAdditionalNotesNotIn(List<String> values) {
			addCriterion("baseprofiletype.additionalNotes not in", values, "additionalNotes");
			return (Criteria) this;
		}

		public Criteria andAdditionalNotesBetween(String value1, String value2) {
			addCriterion("baseprofiletype.additionalNotes between", value1, value2, "additionalNotes");
			return (Criteria) this;
		}

		public Criteria andAdditionalNotesNotBetween(String value1, String value2) {
			addCriterion("baseprofiletype.additionalNotes not between", value1, value2, "additionalNotes");
			return (Criteria) this;
		}

		public Criteria andOwnerNameIsNull() {
			addCriterion("baseprofiletype.ownerName is null");
			return (Criteria) this;
		}

		public Criteria andOwnerNameIsNotNull() {
			addCriterion("baseprofiletype.ownerName is not null");
			return (Criteria) this;
		}

		public Criteria andOwnerNameEqualTo(String value) {
			addCriterion("baseprofiletype.ownerName =", value, "ownerName");
			return (Criteria) this;
		}

		public Criteria andOwnerNameNotEqualTo(String value) {
			addCriterion("baseprofiletype.ownerName <>", value, "ownerName");
			return (Criteria) this;
		}

		public Criteria andOwnerNameGreaterThan(String value) {
			addCriterion("baseprofiletype.ownerName >", value, "ownerName");
			return (Criteria) this;
		}

		public Criteria andOwnerNameGreaterThanOrEqualTo(String value) {
			addCriterion("baseprofiletype.ownerName >=", value, "ownerName");
			return (Criteria) this;
		}

		public Criteria andOwnerNameLessThan(String value) {
			addCriterion("baseprofiletype.ownerName <", value, "ownerName");
			return (Criteria) this;
		}

		public Criteria andOwnerNameLessThanOrEqualTo(String value) {
			addCriterion("baseprofiletype.ownerName <=", value, "ownerName");
			return (Criteria) this;
		}

		public Criteria andOwnerNameLike(String value) {
			addCriterion("baseprofiletype.ownerName like", value, "ownerName");
			return (Criteria) this;
		}

		public Criteria andOwnerNameNotLike(String value) {
			addCriterion("baseprofiletype.ownerName not like", value, "ownerName");
			return (Criteria) this;
		}

		public Criteria andOwnerNameIn(List<String> values) {
			addCriterion("baseprofiletype.ownerName in", values, "ownerName");
			return (Criteria) this;
		}

		public Criteria andOwnerNameNotIn(List<String> values) {
			addCriterion("baseprofiletype.ownerName not in", values, "ownerName");
			return (Criteria) this;
		}

		public Criteria andOwnerNameBetween(String value1, String value2) {
			addCriterion("baseprofiletype.ownerName between", value1, value2, "ownerName");
			return (Criteria) this;
		}

		public Criteria andOwnerNameNotBetween(String value1, String value2) {
			addCriterion("baseprofiletype.ownerName not between", value1, value2, "ownerName");
			return (Criteria) this;
		}

		public Criteria andOrganizationIsNull() {
			addCriterion("baseprofiletype.organization is null");
			return (Criteria) this;
		}

		public Criteria andOrganizationIsNotNull() {
			addCriterion("baseprofiletype.organization is not null");
			return (Criteria) this;
		}

		public Criteria andOrganizationEqualTo(String value) {
			addCriterion("baseprofiletype.organization =", value, "organization");
			return (Criteria) this;
		}

		public Criteria andOrganizationNotEqualTo(String value) {
			addCriterion("baseprofiletype.organization <>", value, "organization");
			return (Criteria) this;
		}

		public Criteria andOrganizationGreaterThan(String value) {
			addCriterion("baseprofiletype.organization >", value, "organization");
			return (Criteria) this;
		}

		public Criteria andOrganizationGreaterThanOrEqualTo(String value) {
			addCriterion("baseprofiletype.organization >=", value, "organization");
			return (Criteria) this;
		}

		public Criteria andOrganizationLessThan(String value) {
			addCriterion("baseprofiletype.organization <", value, "organization");
			return (Criteria) this;
		}

		public Criteria andOrganizationLessThanOrEqualTo(String value) {
			addCriterion("baseprofiletype.organization <=", value, "organization");
			return (Criteria) this;
		}

		public Criteria andOrganizationLike(String value) {
			addCriterion("baseprofiletype.organization like", value, "organization");
			return (Criteria) this;
		}

		public Criteria andOrganizationNotLike(String value) {
			addCriterion("baseprofiletype.organization not like", value, "organization");
			return (Criteria) this;
		}

		public Criteria andOrganizationIn(List<String> values) {
			addCriterion("baseprofiletype.organization in", values, "organization");
			return (Criteria) this;
		}

		public Criteria andOrganizationNotIn(List<String> values) {
			addCriterion("baseprofiletype.organization not in", values, "organization");
			return (Criteria) this;
		}

		public Criteria andOrganizationBetween(String value1, String value2) {
			addCriterion("baseprofiletype.organization between", value1, value2, "organization");
			return (Criteria) this;
		}

		public Criteria andOrganizationNotBetween(String value1, String value2) {
			addCriterion("baseprofiletype.organization not between", value1, value2, "organization");
			return (Criteria) this;
		}

		public Criteria andAccessModifierIsNull() {
			addCriterion("baseprofiletype.accessModifier is null");
			return (Criteria) this;
		}

		public Criteria andAccessModifierIsNotNull() {
			addCriterion("baseprofiletype.accessModifier is not null");
			return (Criteria) this;
		}

		public Criteria andAccessModifierEqualTo(String value) {
			addCriterion("baseprofiletype.accessModifier =", value, "accessModifier");
			return (Criteria) this;
		}

		public Criteria andAccessModifierNotEqualTo(String value) {
			addCriterion("baseprofiletype.accessModifier <>", value, "accessModifier");
			return (Criteria) this;
		}

		public Criteria andAccessModifierGreaterThan(String value) {
			addCriterion("baseprofiletype.accessModifier >", value, "accessModifier");
			return (Criteria) this;
		}

		public Criteria andAccessModifierGreaterThanOrEqualTo(String value) {
			addCriterion("baseprofiletype.accessModifier >=", value, "accessModifier");
			return (Criteria) this;
		}

		public Criteria andAccessModifierLessThan(String value) {
			addCriterion("baseprofiletype.accessModifier <", value, "accessModifier");
			return (Criteria) this;
		}

		public Criteria andAccessModifierLessThanOrEqualTo(String value) {
			addCriterion("baseprofiletype.accessModifier <=", value, "accessModifier");
			return (Criteria) this;
		}

		public Criteria andAccessModifierLike(String value) {
			addCriterion("baseprofiletype.accessModifier like", value, "accessModifier");
			return (Criteria) this;
		}

		public Criteria andAccessModifierNotLike(String value) {
			addCriterion("baseprofiletype.accessModifier not like", value, "accessModifier");
			return (Criteria) this;
		}

		public Criteria andAccessModifierIn(List<String> values) {
			addCriterion("baseprofiletype.accessModifier in", values, "accessModifier");
			return (Criteria) this;
		}

		public Criteria andAccessModifierNotIn(List<String> values) {
			addCriterion("baseprofiletype.accessModifier not in", values, "accessModifier");
			return (Criteria) this;
		}

		public Criteria andAccessModifierBetween(String value1, String value2) {
			addCriterion("baseprofiletype.accessModifier between", value1, value2, "accessModifier");
			return (Criteria) this;
		}

		public Criteria andAccessModifierNotBetween(String value1, String value2) {
			addCriterion("baseprofiletype.accessModifier not between", value1, value2, "accessModifier");
			return (Criteria) this;
		}

		public Criteria andLocationUrlIsNull() {
			addCriterion("baseprofiletype.locationUrl is null");
			return (Criteria) this;
		}

		public Criteria andLocationUrlIsNotNull() {
			addCriterion("baseprofiletype.locationUrl is not null");
			return (Criteria) this;
		}

		public Criteria andLocationUrlEqualTo(String value) {
			addCriterion("baseprofiletype.locationUrl =", value, "locationUrl");
			return (Criteria) this;
		}

		public Criteria andLocationUrlNotEqualTo(String value) {
			addCriterion("baseprofiletype.locationUrl <>", value, "locationUrl");
			return (Criteria) this;
		}

		public Criteria andLocationUrlGreaterThan(String value) {
			addCriterion("baseprofiletype.locationUrl >", value, "locationUrl");
			return (Criteria) this;
		}

		public Criteria andLocationUrlGreaterThanOrEqualTo(String value) {
			addCriterion("baseprofiletype.locationUrl >=", value, "locationUrl");
			return (Criteria) this;
		}

		public Criteria andLocationUrlLessThan(String value) {
			addCriterion("baseprofiletype.locationUrl <", value, "locationUrl");
			return (Criteria) this;
		}

		public Criteria andLocationUrlLessThanOrEqualTo(String value) {
			addCriterion("baseprofiletype.locationUrl <=", value, "locationUrl");
			return (Criteria) this;
		}

		public Criteria andLocationUrlLike(String value) {
			addCriterion("baseprofiletype.locationUrl like", value, "locationUrl");
			return (Criteria) this;
		}

		public Criteria andLocationUrlNotLike(String value) {
			addCriterion("baseprofiletype.locationUrl not like", value, "locationUrl");
			return (Criteria) this;
		}

		public Criteria andLocationUrlIn(List<String> values) {
			addCriterion("baseprofiletype.locationUrl in", values, "locationUrl");
			return (Criteria) this;
		}

		public Criteria andLocationUrlNotIn(List<String> values) {
			addCriterion("baseprofiletype.locationUrl not in", values, "locationUrl");
			return (Criteria) this;
		}

		public Criteria andLocationUrlBetween(String value1, String value2) {
			addCriterion("baseprofiletype.locationUrl between", value1, value2, "locationUrl");
			return (Criteria) this;
		}

		public Criteria andLocationUrlNotBetween(String value1, String value2) {
			addCriterion("baseprofiletype.locationUrl not between", value1, value2, "locationUrl");
			return (Criteria) this;
		}

		public Criteria andParentProfileNameIsNull() {
			addCriterion("baseprofiletype.parentProfileName is null");
			return (Criteria) this;
		}

		public Criteria andParentProfileNameIsNotNull() {
			addCriterion("baseprofiletype.parentProfileName is not null");
			return (Criteria) this;
		}

		public Criteria andParentProfileNameEqualTo(String value) {
			addCriterion("baseprofiletype.parentProfileName =", value, "parentProfileName");
			return (Criteria) this;
		}

		public Criteria andParentProfileNameNotEqualTo(String value) {
			addCriterion("baseprofiletype.parentProfileName <>", value, "parentProfileName");
			return (Criteria) this;
		}

		public Criteria andParentProfileNameGreaterThan(String value) {
			addCriterion("baseprofiletype.parentProfileName >", value, "parentProfileName");
			return (Criteria) this;
		}

		public Criteria andParentProfileNameGreaterThanOrEqualTo(String value) {
			addCriterion("baseprofiletype.parentProfileName >=", value, "parentProfileName");
			return (Criteria) this;
		}

		public Criteria andParentProfileNameLessThan(String value) {
			addCriterion("baseprofiletype.parentProfileName <", value, "parentProfileName");
			return (Criteria) this;
		}

		public Criteria andParentProfileNameLessThanOrEqualTo(String value) {
			addCriterion("baseprofiletype.parentProfileName <=", value, "parentProfileName");
			return (Criteria) this;
		}

		public Criteria andParentProfileNameLike(String value) {
			addCriterion("baseprofiletype.parentProfileName like", value, "parentProfileName");
			return (Criteria) this;
		}

		public Criteria andParentProfileNameNotLike(String value) {
			addCriterion("baseprofiletype.parentProfileName not like", value, "parentProfileName");
			return (Criteria) this;
		}

		public Criteria andParentProfileNameIn(List<String> values) {
			addCriterion("baseprofiletype.parentProfileName in", values, "parentProfileName");
			return (Criteria) this;
		}

		public Criteria andParentProfileNameNotIn(List<String> values) {
			addCriterion("baseprofiletype.parentProfileName not in", values, "parentProfileName");
			return (Criteria) this;
		}

		public Criteria andParentProfileNameBetween(String value1, String value2) {
			addCriterion("baseprofiletype.parentProfileName between", value1, value2, "parentProfileName");
			return (Criteria) this;
		}

		public Criteria andParentProfileNameNotBetween(String value1, String value2) {
			addCriterion("baseprofiletype.parentProfileName not between", value1, value2, "parentProfileName");
			return (Criteria) this;
		}

		public Criteria andIsBaseProfileIsNull() {
			addCriterion("baseprofiletype.IsBaseProfile is null");
			return (Criteria) this;
		}

		public Criteria andIsBaseProfileIsNotNull() {
			addCriterion("baseprofiletype.IsBaseProfile is not null");
			return (Criteria) this;
		}

		public Criteria andIsBaseProfileEqualTo(Boolean value) {
			addCriterion("baseprofiletype.IsBaseProfile =", value, "isBaseProfile");
			return (Criteria) this;
		}

		public Criteria andIsBaseProfileNotEqualTo(Boolean value) {
			addCriterion("baseprofiletype.IsBaseProfile <>", value, "isBaseProfile");
			return (Criteria) this;
		}

		public Criteria andIsBaseProfileGreaterThan(Boolean value) {
			addCriterion("baseprofiletype.IsBaseProfile >", value, "isBaseProfile");
			return (Criteria) this;
		}

		public Criteria andIsBaseProfileGreaterThanOrEqualTo(Boolean value) {
			addCriterion("baseprofiletype.IsBaseProfile >=", value, "isBaseProfile");
			return (Criteria) this;
		}

		public Criteria andIsBaseProfileLessThan(Boolean value) {
			addCriterion("baseprofiletype.IsBaseProfile <", value, "isBaseProfile");
			return (Criteria) this;
		}

		public Criteria andIsBaseProfileLessThanOrEqualTo(Boolean value) {
			addCriterion("baseprofiletype.IsBaseProfile <=", value, "isBaseProfile");
			return (Criteria) this;
		}

		public Criteria andIsBaseProfileIn(List<Boolean> values) {
			addCriterion("baseprofiletype.IsBaseProfile in", values, "isBaseProfile");
			return (Criteria) this;
		}

		public Criteria andIsBaseProfileNotIn(List<Boolean> values) {
			addCriterion("baseprofiletype.IsBaseProfile not in", values, "isBaseProfile");
			return (Criteria) this;
		}

		public Criteria andIsBaseProfileBetween(Boolean value1, Boolean value2) {
			addCriterion("baseprofiletype.IsBaseProfile between", value1, value2, "isBaseProfile");
			return (Criteria) this;
		}

		public Criteria andIsBaseProfileNotBetween(Boolean value1, Boolean value2) {
			addCriterion("baseprofiletype.IsBaseProfile not between", value1, value2, "isBaseProfile");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table baseprofiletype
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table baseprofiletype
     *
     * @mbg.generated do_not_delete_during_merge Thu Jan 18 15:55:27 IST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}