package com.nttdata.fhir.model.mybatis;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class HL7FieldVOExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hl7field
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hl7field
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hl7field
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hl7field
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	public HL7FieldVOExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hl7field
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hl7field
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hl7field
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hl7field
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hl7field
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hl7field
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hl7field
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hl7field
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hl7field
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hl7field
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table hl7field
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andFieldIdIsNull() {
			addCriterion("hl7field.fieldId is null");
			return (Criteria) this;
		}

		public Criteria andFieldIdIsNotNull() {
			addCriterion("hl7field.fieldId is not null");
			return (Criteria) this;
		}

		public Criteria andFieldIdEqualTo(Integer value) {
			addCriterion("hl7field.fieldId =", value, "fieldId");
			return (Criteria) this;
		}

		public Criteria andFieldIdNotEqualTo(Integer value) {
			addCriterion("hl7field.fieldId <>", value, "fieldId");
			return (Criteria) this;
		}

		public Criteria andFieldIdGreaterThan(Integer value) {
			addCriterion("hl7field.fieldId >", value, "fieldId");
			return (Criteria) this;
		}

		public Criteria andFieldIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("hl7field.fieldId >=", value, "fieldId");
			return (Criteria) this;
		}

		public Criteria andFieldIdLessThan(Integer value) {
			addCriterion("hl7field.fieldId <", value, "fieldId");
			return (Criteria) this;
		}

		public Criteria andFieldIdLessThanOrEqualTo(Integer value) {
			addCriterion("hl7field.fieldId <=", value, "fieldId");
			return (Criteria) this;
		}

		public Criteria andFieldIdIn(List<Integer> values) {
			addCriterion("hl7field.fieldId in", values, "fieldId");
			return (Criteria) this;
		}

		public Criteria andFieldIdNotIn(List<Integer> values) {
			addCriterion("hl7field.fieldId not in", values, "fieldId");
			return (Criteria) this;
		}

		public Criteria andFieldIdBetween(Integer value1, Integer value2) {
			addCriterion("hl7field.fieldId between", value1, value2, "fieldId");
			return (Criteria) this;
		}

		public Criteria andFieldIdNotBetween(Integer value1, Integer value2) {
			addCriterion("hl7field.fieldId not between", value1, value2, "fieldId");
			return (Criteria) this;
		}

		public Criteria andSegmentIdIsNull() {
			addCriterion("hl7field.segmentId is null");
			return (Criteria) this;
		}

		public Criteria andSegmentIdIsNotNull() {
			addCriterion("hl7field.segmentId is not null");
			return (Criteria) this;
		}

		public Criteria andSegmentIdEqualTo(Integer value) {
			addCriterion("hl7field.segmentId =", value, "segmentId");
			return (Criteria) this;
		}

		public Criteria andSegmentIdNotEqualTo(Integer value) {
			addCriterion("hl7field.segmentId <>", value, "segmentId");
			return (Criteria) this;
		}

		public Criteria andSegmentIdGreaterThan(Integer value) {
			addCriterion("hl7field.segmentId >", value, "segmentId");
			return (Criteria) this;
		}

		public Criteria andSegmentIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("hl7field.segmentId >=", value, "segmentId");
			return (Criteria) this;
		}

		public Criteria andSegmentIdLessThan(Integer value) {
			addCriterion("hl7field.segmentId <", value, "segmentId");
			return (Criteria) this;
		}

		public Criteria andSegmentIdLessThanOrEqualTo(Integer value) {
			addCriterion("hl7field.segmentId <=", value, "segmentId");
			return (Criteria) this;
		}

		public Criteria andSegmentIdIn(List<Integer> values) {
			addCriterion("hl7field.segmentId in", values, "segmentId");
			return (Criteria) this;
		}

		public Criteria andSegmentIdNotIn(List<Integer> values) {
			addCriterion("hl7field.segmentId not in", values, "segmentId");
			return (Criteria) this;
		}

		public Criteria andSegmentIdBetween(Integer value1, Integer value2) {
			addCriterion("hl7field.segmentId between", value1, value2, "segmentId");
			return (Criteria) this;
		}

		public Criteria andSegmentIdNotBetween(Integer value1, Integer value2) {
			addCriterion("hl7field.segmentId not between", value1, value2, "segmentId");
			return (Criteria) this;
		}

		public Criteria andFieldNameIsNull() {
			addCriterion("hl7field.fieldName is null");
			return (Criteria) this;
		}

		public Criteria andFieldNameIsNotNull() {
			addCriterion("hl7field.fieldName is not null");
			return (Criteria) this;
		}

		public Criteria andFieldNameEqualTo(String value) {
			addCriterion("hl7field.fieldName =", value, "fieldName");
			return (Criteria) this;
		}

		public Criteria andFieldNameNotEqualTo(String value) {
			addCriterion("hl7field.fieldName <>", value, "fieldName");
			return (Criteria) this;
		}

		public Criteria andFieldNameGreaterThan(String value) {
			addCriterion("hl7field.fieldName >", value, "fieldName");
			return (Criteria) this;
		}

		public Criteria andFieldNameGreaterThanOrEqualTo(String value) {
			addCriterion("hl7field.fieldName >=", value, "fieldName");
			return (Criteria) this;
		}

		public Criteria andFieldNameLessThan(String value) {
			addCriterion("hl7field.fieldName <", value, "fieldName");
			return (Criteria) this;
		}

		public Criteria andFieldNameLessThanOrEqualTo(String value) {
			addCriterion("hl7field.fieldName <=", value, "fieldName");
			return (Criteria) this;
		}

		public Criteria andFieldNameLike(String value) {
			addCriterion("hl7field.fieldName like", value, "fieldName");
			return (Criteria) this;
		}

		public Criteria andFieldNameNotLike(String value) {
			addCriterion("hl7field.fieldName not like", value, "fieldName");
			return (Criteria) this;
		}

		public Criteria andFieldNameIn(List<String> values) {
			addCriterion("hl7field.fieldName in", values, "fieldName");
			return (Criteria) this;
		}

		public Criteria andFieldNameNotIn(List<String> values) {
			addCriterion("hl7field.fieldName not in", values, "fieldName");
			return (Criteria) this;
		}

		public Criteria andFieldNameBetween(String value1, String value2) {
			addCriterion("hl7field.fieldName between", value1, value2, "fieldName");
			return (Criteria) this;
		}

		public Criteria andFieldNameNotBetween(String value1, String value2) {
			addCriterion("hl7field.fieldName not between", value1, value2, "fieldName");
			return (Criteria) this;
		}

		public Criteria andIsActiveIsNull() {
			addCriterion("hl7field.isActive is null");
			return (Criteria) this;
		}

		public Criteria andIsActiveIsNotNull() {
			addCriterion("hl7field.isActive is not null");
			return (Criteria) this;
		}

		public Criteria andIsActiveEqualTo(Boolean value) {
			addCriterion("hl7field.isActive =", value, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveNotEqualTo(Boolean value) {
			addCriterion("hl7field.isActive <>", value, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveGreaterThan(Boolean value) {
			addCriterion("hl7field.isActive >", value, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveGreaterThanOrEqualTo(Boolean value) {
			addCriterion("hl7field.isActive >=", value, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveLessThan(Boolean value) {
			addCriterion("hl7field.isActive <", value, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveLessThanOrEqualTo(Boolean value) {
			addCriterion("hl7field.isActive <=", value, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveIn(List<Boolean> values) {
			addCriterion("hl7field.isActive in", values, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveNotIn(List<Boolean> values) {
			addCriterion("hl7field.isActive not in", values, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveBetween(Boolean value1, Boolean value2) {
			addCriterion("hl7field.isActive between", value1, value2, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveNotBetween(Boolean value1, Boolean value2) {
			addCriterion("hl7field.isActive not between", value1, value2, "isActive");
			return (Criteria) this;
		}

		public Criteria andCreatedOnIsNull() {
			addCriterion("hl7field.createdOn is null");
			return (Criteria) this;
		}

		public Criteria andCreatedOnIsNotNull() {
			addCriterion("hl7field.createdOn is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedOnEqualTo(Date value) {
			addCriterion("hl7field.createdOn =", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnNotEqualTo(Date value) {
			addCriterion("hl7field.createdOn <>", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnGreaterThan(Date value) {
			addCriterion("hl7field.createdOn >", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnGreaterThanOrEqualTo(Date value) {
			addCriterion("hl7field.createdOn >=", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnLessThan(Date value) {
			addCriterion("hl7field.createdOn <", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnLessThanOrEqualTo(Date value) {
			addCriterion("hl7field.createdOn <=", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnIn(List<Date> values) {
			addCriterion("hl7field.createdOn in", values, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnNotIn(List<Date> values) {
			addCriterion("hl7field.createdOn not in", values, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnBetween(Date value1, Date value2) {
			addCriterion("hl7field.createdOn between", value1, value2, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnNotBetween(Date value1, Date value2) {
			addCriterion("hl7field.createdOn not between", value1, value2, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedByIsNull() {
			addCriterion("hl7field.createdBy is null");
			return (Criteria) this;
		}

		public Criteria andCreatedByIsNotNull() {
			addCriterion("hl7field.createdBy is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedByEqualTo(String value) {
			addCriterion("hl7field.createdBy =", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByNotEqualTo(String value) {
			addCriterion("hl7field.createdBy <>", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByGreaterThan(String value) {
			addCriterion("hl7field.createdBy >", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
			addCriterion("hl7field.createdBy >=", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByLessThan(String value) {
			addCriterion("hl7field.createdBy <", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByLessThanOrEqualTo(String value) {
			addCriterion("hl7field.createdBy <=", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByLike(String value) {
			addCriterion("hl7field.createdBy like", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByNotLike(String value) {
			addCriterion("hl7field.createdBy not like", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByIn(List<String> values) {
			addCriterion("hl7field.createdBy in", values, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByNotIn(List<String> values) {
			addCriterion("hl7field.createdBy not in", values, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByBetween(String value1, String value2) {
			addCriterion("hl7field.createdBy between", value1, value2, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByNotBetween(String value1, String value2) {
			addCriterion("hl7field.createdBy not between", value1, value2, "createdBy");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table hl7field
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hl7field
     *
     * @mbg.generated do_not_delete_during_merge Thu Jan 18 15:55:27 IST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}