package com.nttdata.fhir.model.mybatis;

import com.nttdata.fhir.model.DataObject;
import java.io.Serializable;
import java.util.Date;

public class HL7SegmentVO extends DataObject implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hl7segment.segmentId
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	private Integer segmentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hl7segment.segmentName
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	private String segmentName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hl7segment.isActive
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	private Boolean isActive;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hl7segment
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hl7segment.segmentId
	 * @return  the value of hl7segment.segmentId
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public Integer getSegmentId() {
		return segmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hl7segment.segmentId
	 * @param segmentId  the value for hl7segment.segmentId
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public void setSegmentId(Integer segmentId) {
		this.segmentId = segmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hl7segment.segmentName
	 * @return  the value of hl7segment.segmentName
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public String getSegmentName() {
		return segmentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hl7segment.segmentName
	 * @param segmentName  the value for hl7segment.segmentName
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public void setSegmentName(String segmentName) {
		this.segmentName = segmentName == null ? null : segmentName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hl7segment.isActive
	 * @return  the value of hl7segment.isActive
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public Boolean getIsActive() {
		return isActive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hl7segment.isActive
	 * @param isActive  the value for hl7segment.isActive
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}
}