package com.nttdata.fhir.model.mybatis;

import java.util.ArrayList;
import java.util.List;

public class ProfileFieldVOExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table profilefield
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table profilefield
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table profilefield
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table profilefield
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	public ProfileFieldVOExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table profilefield
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table profilefield
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table profilefield
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table profilefield
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table profilefield
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table profilefield
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table profilefield
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table profilefield
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table profilefield
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table profilefield
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table profilefield
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("profilefield.id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("profilefield.id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("profilefield.id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("profilefield.id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("profilefield.id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("profilefield.id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("profilefield.id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("profilefield.id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("profilefield.id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("profilefield.id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("profilefield.id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("profilefield.id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andProfileTypeIdIsNull() {
			addCriterion("profilefield.profileTypeId is null");
			return (Criteria) this;
		}

		public Criteria andProfileTypeIdIsNotNull() {
			addCriterion("profilefield.profileTypeId is not null");
			return (Criteria) this;
		}

		public Criteria andProfileTypeIdEqualTo(Integer value) {
			addCriterion("profilefield.profileTypeId =", value, "profileTypeId");
			return (Criteria) this;
		}

		public Criteria andProfileTypeIdNotEqualTo(Integer value) {
			addCriterion("profilefield.profileTypeId <>", value, "profileTypeId");
			return (Criteria) this;
		}

		public Criteria andProfileTypeIdGreaterThan(Integer value) {
			addCriterion("profilefield.profileTypeId >", value, "profileTypeId");
			return (Criteria) this;
		}

		public Criteria andProfileTypeIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("profilefield.profileTypeId >=", value, "profileTypeId");
			return (Criteria) this;
		}

		public Criteria andProfileTypeIdLessThan(Integer value) {
			addCriterion("profilefield.profileTypeId <", value, "profileTypeId");
			return (Criteria) this;
		}

		public Criteria andProfileTypeIdLessThanOrEqualTo(Integer value) {
			addCriterion("profilefield.profileTypeId <=", value, "profileTypeId");
			return (Criteria) this;
		}

		public Criteria andProfileTypeIdIn(List<Integer> values) {
			addCriterion("profilefield.profileTypeId in", values, "profileTypeId");
			return (Criteria) this;
		}

		public Criteria andProfileTypeIdNotIn(List<Integer> values) {
			addCriterion("profilefield.profileTypeId not in", values, "profileTypeId");
			return (Criteria) this;
		}

		public Criteria andProfileTypeIdBetween(Integer value1, Integer value2) {
			addCriterion("profilefield.profileTypeId between", value1, value2, "profileTypeId");
			return (Criteria) this;
		}

		public Criteria andProfileTypeIdNotBetween(Integer value1, Integer value2) {
			addCriterion("profilefield.profileTypeId not between", value1, value2, "profileTypeId");
			return (Criteria) this;
		}

		public Criteria andResourceIdIsNull() {
			addCriterion("profilefield.resourceId is null");
			return (Criteria) this;
		}

		public Criteria andResourceIdIsNotNull() {
			addCriterion("profilefield.resourceId is not null");
			return (Criteria) this;
		}

		public Criteria andResourceIdEqualTo(Integer value) {
			addCriterion("profilefield.resourceId =", value, "resourceId");
			return (Criteria) this;
		}

		public Criteria andResourceIdNotEqualTo(Integer value) {
			addCriterion("profilefield.resourceId <>", value, "resourceId");
			return (Criteria) this;
		}

		public Criteria andResourceIdGreaterThan(Integer value) {
			addCriterion("profilefield.resourceId >", value, "resourceId");
			return (Criteria) this;
		}

		public Criteria andResourceIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("profilefield.resourceId >=", value, "resourceId");
			return (Criteria) this;
		}

		public Criteria andResourceIdLessThan(Integer value) {
			addCriterion("profilefield.resourceId <", value, "resourceId");
			return (Criteria) this;
		}

		public Criteria andResourceIdLessThanOrEqualTo(Integer value) {
			addCriterion("profilefield.resourceId <=", value, "resourceId");
			return (Criteria) this;
		}

		public Criteria andResourceIdIn(List<Integer> values) {
			addCriterion("profilefield.resourceId in", values, "resourceId");
			return (Criteria) this;
		}

		public Criteria andResourceIdNotIn(List<Integer> values) {
			addCriterion("profilefield.resourceId not in", values, "resourceId");
			return (Criteria) this;
		}

		public Criteria andResourceIdBetween(Integer value1, Integer value2) {
			addCriterion("profilefield.resourceId between", value1, value2, "resourceId");
			return (Criteria) this;
		}

		public Criteria andResourceIdNotBetween(Integer value1, Integer value2) {
			addCriterion("profilefield.resourceId not between", value1, value2, "resourceId");
			return (Criteria) this;
		}

		public Criteria andFieldNameIsNull() {
			addCriterion("profilefield.fieldName is null");
			return (Criteria) this;
		}

		public Criteria andFieldNameIsNotNull() {
			addCriterion("profilefield.fieldName is not null");
			return (Criteria) this;
		}

		public Criteria andFieldNameEqualTo(String value) {
			addCriterion("profilefield.fieldName =", value, "fieldName");
			return (Criteria) this;
		}

		public Criteria andFieldNameNotEqualTo(String value) {
			addCriterion("profilefield.fieldName <>", value, "fieldName");
			return (Criteria) this;
		}

		public Criteria andFieldNameGreaterThan(String value) {
			addCriterion("profilefield.fieldName >", value, "fieldName");
			return (Criteria) this;
		}

		public Criteria andFieldNameGreaterThanOrEqualTo(String value) {
			addCriterion("profilefield.fieldName >=", value, "fieldName");
			return (Criteria) this;
		}

		public Criteria andFieldNameLessThan(String value) {
			addCriterion("profilefield.fieldName <", value, "fieldName");
			return (Criteria) this;
		}

		public Criteria andFieldNameLessThanOrEqualTo(String value) {
			addCriterion("profilefield.fieldName <=", value, "fieldName");
			return (Criteria) this;
		}

		public Criteria andFieldNameLike(String value) {
			addCriterion("profilefield.fieldName like", value, "fieldName");
			return (Criteria) this;
		}

		public Criteria andFieldNameNotLike(String value) {
			addCriterion("profilefield.fieldName not like", value, "fieldName");
			return (Criteria) this;
		}

		public Criteria andFieldNameIn(List<String> values) {
			addCriterion("profilefield.fieldName in", values, "fieldName");
			return (Criteria) this;
		}

		public Criteria andFieldNameNotIn(List<String> values) {
			addCriterion("profilefield.fieldName not in", values, "fieldName");
			return (Criteria) this;
		}

		public Criteria andFieldNameBetween(String value1, String value2) {
			addCriterion("profilefield.fieldName between", value1, value2, "fieldName");
			return (Criteria) this;
		}

		public Criteria andFieldNameNotBetween(String value1, String value2) {
			addCriterion("profilefield.fieldName not between", value1, value2, "fieldName");
			return (Criteria) this;
		}

		public Criteria andStaticValuesIsNull() {
			addCriterion("profilefield.staticValues is null");
			return (Criteria) this;
		}

		public Criteria andStaticValuesIsNotNull() {
			addCriterion("profilefield.staticValues is not null");
			return (Criteria) this;
		}

		public Criteria andStaticValuesEqualTo(String value) {
			addCriterion("profilefield.staticValues =", value, "staticValues");
			return (Criteria) this;
		}

		public Criteria andStaticValuesNotEqualTo(String value) {
			addCriterion("profilefield.staticValues <>", value, "staticValues");
			return (Criteria) this;
		}

		public Criteria andStaticValuesGreaterThan(String value) {
			addCriterion("profilefield.staticValues >", value, "staticValues");
			return (Criteria) this;
		}

		public Criteria andStaticValuesGreaterThanOrEqualTo(String value) {
			addCriterion("profilefield.staticValues >=", value, "staticValues");
			return (Criteria) this;
		}

		public Criteria andStaticValuesLessThan(String value) {
			addCriterion("profilefield.staticValues <", value, "staticValues");
			return (Criteria) this;
		}

		public Criteria andStaticValuesLessThanOrEqualTo(String value) {
			addCriterion("profilefield.staticValues <=", value, "staticValues");
			return (Criteria) this;
		}

		public Criteria andStaticValuesLike(String value) {
			addCriterion("profilefield.staticValues like", value, "staticValues");
			return (Criteria) this;
		}

		public Criteria andStaticValuesNotLike(String value) {
			addCriterion("profilefield.staticValues not like", value, "staticValues");
			return (Criteria) this;
		}

		public Criteria andStaticValuesIn(List<String> values) {
			addCriterion("profilefield.staticValues in", values, "staticValues");
			return (Criteria) this;
		}

		public Criteria andStaticValuesNotIn(List<String> values) {
			addCriterion("profilefield.staticValues not in", values, "staticValues");
			return (Criteria) this;
		}

		public Criteria andStaticValuesBetween(String value1, String value2) {
			addCriterion("profilefield.staticValues between", value1, value2, "staticValues");
			return (Criteria) this;
		}

		public Criteria andStaticValuesNotBetween(String value1, String value2) {
			addCriterion("profilefield.staticValues not between", value1, value2, "staticValues");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNull() {
			addCriterion("profilefield.description is null");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNotNull() {
			addCriterion("profilefield.description is not null");
			return (Criteria) this;
		}

		public Criteria andDescriptionEqualTo(String value) {
			addCriterion("profilefield.description =", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotEqualTo(String value) {
			addCriterion("profilefield.description <>", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThan(String value) {
			addCriterion("profilefield.description >", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("profilefield.description >=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThan(String value) {
			addCriterion("profilefield.description <", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThanOrEqualTo(String value) {
			addCriterion("profilefield.description <=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLike(String value) {
			addCriterion("profilefield.description like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotLike(String value) {
			addCriterion("profilefield.description not like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionIn(List<String> values) {
			addCriterion("profilefield.description in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotIn(List<String> values) {
			addCriterion("profilefield.description not in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionBetween(String value1, String value2) {
			addCriterion("profilefield.description between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotBetween(String value1, String value2) {
			addCriterion("profilefield.description not between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andIsRequiredIsNull() {
			addCriterion("profilefield.isRequired is null");
			return (Criteria) this;
		}

		public Criteria andIsRequiredIsNotNull() {
			addCriterion("profilefield.isRequired is not null");
			return (Criteria) this;
		}

		public Criteria andIsRequiredEqualTo(Boolean value) {
			addCriterion("profilefield.isRequired =", value, "isRequired");
			return (Criteria) this;
		}

		public Criteria andIsRequiredNotEqualTo(Boolean value) {
			addCriterion("profilefield.isRequired <>", value, "isRequired");
			return (Criteria) this;
		}

		public Criteria andIsRequiredGreaterThan(Boolean value) {
			addCriterion("profilefield.isRequired >", value, "isRequired");
			return (Criteria) this;
		}

		public Criteria andIsRequiredGreaterThanOrEqualTo(Boolean value) {
			addCriterion("profilefield.isRequired >=", value, "isRequired");
			return (Criteria) this;
		}

		public Criteria andIsRequiredLessThan(Boolean value) {
			addCriterion("profilefield.isRequired <", value, "isRequired");
			return (Criteria) this;
		}

		public Criteria andIsRequiredLessThanOrEqualTo(Boolean value) {
			addCriterion("profilefield.isRequired <=", value, "isRequired");
			return (Criteria) this;
		}

		public Criteria andIsRequiredIn(List<Boolean> values) {
			addCriterion("profilefield.isRequired in", values, "isRequired");
			return (Criteria) this;
		}

		public Criteria andIsRequiredNotIn(List<Boolean> values) {
			addCriterion("profilefield.isRequired not in", values, "isRequired");
			return (Criteria) this;
		}

		public Criteria andIsRequiredBetween(Boolean value1, Boolean value2) {
			addCriterion("profilefield.isRequired between", value1, value2, "isRequired");
			return (Criteria) this;
		}

		public Criteria andIsRequiredNotBetween(Boolean value1, Boolean value2) {
			addCriterion("profilefield.isRequired not between", value1, value2, "isRequired");
			return (Criteria) this;
		}

		public Criteria andIsRepeatingIsNull() {
			addCriterion("profilefield.isRepeating is null");
			return (Criteria) this;
		}

		public Criteria andIsRepeatingIsNotNull() {
			addCriterion("profilefield.isRepeating is not null");
			return (Criteria) this;
		}

		public Criteria andIsRepeatingEqualTo(Boolean value) {
			addCriterion("profilefield.isRepeating =", value, "isRepeating");
			return (Criteria) this;
		}

		public Criteria andIsRepeatingNotEqualTo(Boolean value) {
			addCriterion("profilefield.isRepeating <>", value, "isRepeating");
			return (Criteria) this;
		}

		public Criteria andIsRepeatingGreaterThan(Boolean value) {
			addCriterion("profilefield.isRepeating >", value, "isRepeating");
			return (Criteria) this;
		}

		public Criteria andIsRepeatingGreaterThanOrEqualTo(Boolean value) {
			addCriterion("profilefield.isRepeating >=", value, "isRepeating");
			return (Criteria) this;
		}

		public Criteria andIsRepeatingLessThan(Boolean value) {
			addCriterion("profilefield.isRepeating <", value, "isRepeating");
			return (Criteria) this;
		}

		public Criteria andIsRepeatingLessThanOrEqualTo(Boolean value) {
			addCriterion("profilefield.isRepeating <=", value, "isRepeating");
			return (Criteria) this;
		}

		public Criteria andIsRepeatingIn(List<Boolean> values) {
			addCriterion("profilefield.isRepeating in", values, "isRepeating");
			return (Criteria) this;
		}

		public Criteria andIsRepeatingNotIn(List<Boolean> values) {
			addCriterion("profilefield.isRepeating not in", values, "isRepeating");
			return (Criteria) this;
		}

		public Criteria andIsRepeatingBetween(Boolean value1, Boolean value2) {
			addCriterion("profilefield.isRepeating between", value1, value2, "isRepeating");
			return (Criteria) this;
		}

		public Criteria andIsRepeatingNotBetween(Boolean value1, Boolean value2) {
			addCriterion("profilefield.isRepeating not between", value1, value2, "isRepeating");
			return (Criteria) this;
		}

		public Criteria andIsExtensionIsNull() {
			addCriterion("profilefield.isExtension is null");
			return (Criteria) this;
		}

		public Criteria andIsExtensionIsNotNull() {
			addCriterion("profilefield.isExtension is not null");
			return (Criteria) this;
		}

		public Criteria andIsExtensionEqualTo(Boolean value) {
			addCriterion("profilefield.isExtension =", value, "isExtension");
			return (Criteria) this;
		}

		public Criteria andIsExtensionNotEqualTo(Boolean value) {
			addCriterion("profilefield.isExtension <>", value, "isExtension");
			return (Criteria) this;
		}

		public Criteria andIsExtensionGreaterThan(Boolean value) {
			addCriterion("profilefield.isExtension >", value, "isExtension");
			return (Criteria) this;
		}

		public Criteria andIsExtensionGreaterThanOrEqualTo(Boolean value) {
			addCriterion("profilefield.isExtension >=", value, "isExtension");
			return (Criteria) this;
		}

		public Criteria andIsExtensionLessThan(Boolean value) {
			addCriterion("profilefield.isExtension <", value, "isExtension");
			return (Criteria) this;
		}

		public Criteria andIsExtensionLessThanOrEqualTo(Boolean value) {
			addCriterion("profilefield.isExtension <=", value, "isExtension");
			return (Criteria) this;
		}

		public Criteria andIsExtensionIn(List<Boolean> values) {
			addCriterion("profilefield.isExtension in", values, "isExtension");
			return (Criteria) this;
		}

		public Criteria andIsExtensionNotIn(List<Boolean> values) {
			addCriterion("profilefield.isExtension not in", values, "isExtension");
			return (Criteria) this;
		}

		public Criteria andIsExtensionBetween(Boolean value1, Boolean value2) {
			addCriterion("profilefield.isExtension between", value1, value2, "isExtension");
			return (Criteria) this;
		}

		public Criteria andIsExtensionNotBetween(Boolean value1, Boolean value2) {
			addCriterion("profilefield.isExtension not between", value1, value2, "isExtension");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table profilefield
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table profilefield
     *
     * @mbg.generated do_not_delete_during_merge Fri Jan 19 14:49:43 IST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}