package com.nttdata.fhir.model.mybatis;

import com.nttdata.fhir.model.DataObject;
import java.io.Serializable;
import java.util.Date;

public class ResourceVO extends DataObject implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.id
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.name
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.description
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.isActive
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	private Boolean isActive;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table resource
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.id
	 * @return  the value of resource.id
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.id
	 * @param id  the value for resource.id
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.name
	 * @return  the value of resource.name
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.name
	 * @param name  the value for resource.name
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.description
	 * @return  the value of resource.description
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.description
	 * @param description  the value for resource.description
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.isActive
	 * @return  the value of resource.isActive
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	public Boolean getIsActive() {
		return isActive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.isActive
	 * @param isActive  the value for resource.isActive
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}
}