package com.nttdata.fhir.model.mybatis;

import com.nttdata.fhir.model.DataObject;
import java.io.Serializable;

public class WorkflowStatusVO extends DataObject implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column workflowstatus.id
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column workflowstatus.statusCode
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	private String statusCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column workflowstatus.statusName
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	private String statusName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column workflowstatus.isActive
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	private Boolean isActive;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column workflowstatus.description
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column workflowstatus.notes
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	private String notes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table workflowstatus
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column workflowstatus.id
	 * @return  the value of workflowstatus.id
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column workflowstatus.id
	 * @param id  the value for workflowstatus.id
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column workflowstatus.statusCode
	 * @return  the value of workflowstatus.statusCode
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public String getStatusCode() {
		return statusCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column workflowstatus.statusCode
	 * @param statusCode  the value for workflowstatus.statusCode
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public void setStatusCode(String statusCode) {
		this.statusCode = statusCode == null ? null : statusCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column workflowstatus.statusName
	 * @return  the value of workflowstatus.statusName
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public String getStatusName() {
		return statusName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column workflowstatus.statusName
	 * @param statusName  the value for workflowstatus.statusName
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public void setStatusName(String statusName) {
		this.statusName = statusName == null ? null : statusName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column workflowstatus.isActive
	 * @return  the value of workflowstatus.isActive
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public Boolean getIsActive() {
		return isActive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column workflowstatus.isActive
	 * @param isActive  the value for workflowstatus.isActive
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column workflowstatus.description
	 * @return  the value of workflowstatus.description
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column workflowstatus.description
	 * @param description  the value for workflowstatus.description
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column workflowstatus.notes
	 * @return  the value of workflowstatus.notes
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public String getNotes() {
		return notes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column workflowstatus.notes
	 * @param notes  the value for workflowstatus.notes
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	public void setNotes(String notes) {
		this.notes = notes == null ? null : notes.trim();
	}
}