package com.nttdata.fhir.dao.mybatis;

import com.nttdata.fhir.model.mybatis.HL7FieldVO;
import com.nttdata.fhir.model.mybatis.HL7FieldVOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HL7FieldVOMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hl7field
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	long countByExample(HL7FieldVOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hl7field
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	int deleteByExample(HL7FieldVOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hl7field
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	int insert(HL7FieldVO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hl7field
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	int insertSelective(HL7FieldVO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hl7field
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	List<HL7FieldVO> selectByExample(HL7FieldVOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hl7field
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	int updateByExampleSelective(@Param("record") HL7FieldVO record, @Param("example") HL7FieldVOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hl7field
	 * @mbg.generated  Tue Jan 23 20:49:41 IST 2018
	 */
	int updateByExample(@Param("record") HL7FieldVO record, @Param("example") HL7FieldVOExample example);
}