package com.nttdata.fhir.dao.mybatis;

import com.nttdata.fhir.model.mybatis.ProfileFieldVO;
import com.nttdata.fhir.model.mybatis.ProfileFieldVOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProfileFieldVOMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table profilefield
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	long countByExample(ProfileFieldVOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table profilefield
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	int deleteByExample(ProfileFieldVOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table profilefield
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	int insert(ProfileFieldVO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table profilefield
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	int insertSelective(ProfileFieldVO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table profilefield
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	List<ProfileFieldVO> selectByExample(ProfileFieldVOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table profilefield
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	int updateByExampleSelective(@Param("record") ProfileFieldVO record,
			@Param("example") ProfileFieldVOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table profilefield
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	int updateByExample(@Param("record") ProfileFieldVO record, @Param("example") ProfileFieldVOExample example);
}