package com.nttdata.fhir.dao.mybatis;

import com.nttdata.fhir.model.mybatis.RoleVO;
import com.nttdata.fhir.model.mybatis.RoleVOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleVOMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	long countByExample(RoleVOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	int deleteByExample(RoleVOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	int insert(RoleVO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	int insertSelective(RoleVO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	List<RoleVO> selectByExample(RoleVOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	int updateByExampleSelective(@Param("record") RoleVO record, @Param("example") RoleVOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role
	 * @mbg.generated  Thu Feb 01 14:43:52 IST 2018
	 */
	int updateByExample(@Param("record") RoleVO record, @Param("example") RoleVOExample example);
}