package com.nttdata.fhir.dao.mybatis;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.nttdata.fhir.model.mybatis.WorkflowVO;
import com.nttdata.fhir.model.mybatis.WorkflowVOExample;

public interface WorkflowVOMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table workflow
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	long countByExample(WorkflowVOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table workflow
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	int deleteByExample(WorkflowVOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table workflow
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	int insert(WorkflowVO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table workflow
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	int insertSelective(WorkflowVO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table workflow
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	List<WorkflowVO> selectByExample(WorkflowVOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table workflow
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	int updateByExampleSelective(@Param("record") WorkflowVO record, @Param("example") WorkflowVOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table workflow
	 * @mbg.generated  Tue Mar 06 15:17:26 IST 2018
	 */
	int updateByExample(@Param("record") WorkflowVO record, @Param("example") WorkflowVOExample example);

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow
     *
     */
    int deleteByPrimaryKey(int id);

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow
     *
     */
    WorkflowVO selectByPrimaryKey(int id);

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow
     *
     */
    int updateByPrimaryKey(WorkflowVO record);
}